LFS_BUCKET: obs-self-host-lfs-test
AWS_REGION: obs.cn-north-4.myhuaweicloud.com
AWS_ACCESS_KEY_ID: XKNAFWQQ9J303CFDDHU2
AWS_SECRET_ACCESS_KEY: QzX85p0MIsaYGKvDppKQYkx7dhf6FbCCOSqj7kkm
CLIENT_ID: 745a010d834dbf7b9cbec28c93a867152f6fec7b5fa4c8e88639c13554f2d29c
CLIENT_SECRET: 233f59671ef9ed528f4ab77e8eb826b9ef933d2ff0fdc3ae75dbb23a33ec3104
PATH_PREFIX: huawei-lfs-test
