name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ '*' ]
env:
  GOPRIVATE: "github.com/opensourceways"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run e2e tests
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_USER: ${{ secrets.USER }}
        run: bash -x scripts/init-env.sh && bash -x scripts/openapi.sh && cd tests/e2e && go test -v -count=1 ./...
      - name: Self Hosted Runner Post Job Cleanup Action
        uses: TooMuch4U/actions-clean@master
      - name: cleanup
        run: rm -f ~/.netrc