name: Check Moderation Tag

on:
  workflow_dispatch:
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v4
      - name: Run moderation tag check script
        run: cd scripts && bash -x moderation_tag_check.sh
      - name: Self Hosted Runner Post Job Cleanup Action
        uses: TooMuch4U/actions-clean@master
